project:
  type: website
  output-dir: _site
  resources:
    - "assets/**"
    - "shared/reveal/**"
    - "ru/slides/media/**"
    - "en/slides/media/**"

lang: ru-RU

website:
  title: "Квантовая теория поля"
  site-url: "https://neutrinohit.github.io/qft-lectures/"
  repo-url: "https://github.com/NeutrinoHit/qft-lectures"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    include-after-body: analytics/cloudflare-web-analytics.html
